version: '3.6'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "test `psql -U postgres tsukedaicho_test -c '\\dt' -t | wc -l` = 3"]
      interval: 1s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  hasura: &hasura
    container_name: hasura
    image: hasura/graphql-engine:v2.3.1.cli-migrations-v3
    ports:
      - "20080:8080"
    volumes:
      - ./hasura/metadata:/hasura-metadata
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    environment: &environment
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgresql:5432/tsukedaicho
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
  hasura-test:
    <<: *hasura
    container_name: hasura-test
    ports:
      - "20081:8080"
    environment:
      <<: *environment
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgresql:5432/tsukedaicho_test
